### ISSUE TITLE
Config: add option to select a type of a Framework (GoogleTest, Rust, etc).

### ISSUE THREAD

**Issue by stanislaw** [mull-project/mull#112]
1) This is the example of what we need in config.yml:

```yaml
test_framework:
  type: Rust  
  version: 1.0.1 # this is not needed currently, just an example
```

or 

```yaml
test_framework:
  type: GoogleTest
```

2) Implement validation checks for supported frameworks.

Currently we support: `Rust`, `GoogleTest`, `SimpleTest`. `GoogleTest` should be default for now.

3) Integrate this to `mull-driver` so that it recognizes `config.yml` with this option.
